name: Continuous Integration (push)

on:
  push:
  workflow_dispatch:

jobs:
  check-dispatch:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch') }}
    steps:
      - run: echo "dispach"

  check-push:
    runs-on: ubuntu-latest

    steps:
      - run: echo "push"
